name: Test

on:
  push:
    branches: 
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      is_upgraded: ${{ steps.step1.outputs.is_upgraded }}
      package_version: ${{ steps.step1.outputs.is_upgraded }}
    steps:
      - uses: actions/checkout@v2
      - uses: thieryw/check-version-upgrade@v1.0.1
        id: "step1"

  test2:
    runs-on: ubuntu-latest
    needs: test
    env:
      PACKAGE_VERSION: ${{ needs.test.outputs.package_version }}
    steps:
     - uses: actions/checkout@v2
     - run: echo $PACKAGE_VERSION