name: Test

on:
  push:
    branches: 
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      is_upgraded: ${{ steps.step1.outputs.is_upgraded }}
    steps:
      - uses: actions/checkout@v2
      - uses: thieryw/check-version-upgrade@v1.0.2
        id: "step1"
        with:
          repo_name: gitlanding
          repo_owner: thieryw
          branch: f1fd26aebfa290946ad872773681252f8c903073

  test2:
    runs-on: ubuntu-latest
    needs: test
    env:
      IS_UPGRADED: ${{ needs.test.outputs.is_upgraded }}
    steps:
     - uses: actions/checkout@v2
     - run: echo $IS_UPGRADED